
services:
  backend:
    build:
      context: ./back/calculator-back
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development 

  frontend:
    build:
      context: ./front/calculator-front
    ports:
      - "80:80"
    depends_on:
      - backend
